### ISSUE TITLE
Books api not including author information

### ISSUE THREAD

**Issue by hoverruan** [wahyd4/Libr#2]
The author field is always null:

{"author":null,"created_at":"2013-02-16T21:02:40+08:00","id":131,"image":"http://img3.douban.com/mpic/s11352335.jpg","isbn":"9787121077012","name":"Ruby\u7f16\u7a0b\u8bed\u8a00","updated_at":"2013-02-16T21:02:40+08:00"}

**Comment by wahyd4** [comment]
之前添加到系统的书书没有作者信息的，后面我修改了API，现在才会记录书籍的作者信息。因此之前的大概100本都没得作者信息。就暂时显示无吧。你看怎么样？
