### ISSUE TITLE
请问如何添加图书？

### ISSUE THREAD

**Issue by lgyjg** [wahyd4/Libr#7]
是不是通过后台添加？如果是，那后台的默认密码是多少呢？

我登录到如下地址的后台，进去使用注册的用户名密码不能登录，报出以下错误：

登录地址：http://localhost:3000/admin/login

```
Can't mass-assign protected attributes for AdminUser: remember_me

Rails.root: /home/ts/githubPro/Libr

Application Trace | Framework Trace | Full Trace
Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"TZmlgNw42ks/V5GniB30crHCrdW7UDS5KvVwccFy3Y1=",
 "admin_user"=>{"email"=>"user@admin.com",
 "password"=>"[FILTERED]",
 "remember_me"=>"1"},
 "commit"=>"Login"}
```

**Comment by wahyd4** [comment]
libr需要通过豆瓣来导入书籍。管理员账号和密码是依赖于一个第三方gem，你可以在gemfile里面自己找
yangjg <notifications@github.com>于2017年2月16日 周四下午11:15写道：

**Comment by lgyjg** [comment]
使用了：[activeadmin gem](https://github.com/activeadmin/activeadmin)
``` yml
#admin interface
gem 'activeadmin', github: 'gregbell/active_admin'
```

> Visit http://localhost:3000/admin and log in as the default user:
> User: admin@example.com
> Password: password
(详见：https://github.com/activeadmin/activeadmin)
